name = "xandikos"
tag-name = "v$VERSION"
news-file = "NEWS"
verify-command = "make check"
tarball-location = []
release-timeout = 5

[[update_version]]
path = "xandikos/__init__.py"
match = "^__version__ = ((.*))$"
new-line = "__version__ = $TUPLED_VERSION"

[[update_version]]
path = "Cargo.toml"
match = '^version = "(.*)"$'
new-line = 'version = "$VERSION"'

[github]
url = "https://github.com/jelmer/xandikos"
