---
version: "3.4"

services:
  xandikos:
    image: ghcr.io/jelmer/xandikos
    ports:
      - 8000:8000
      - 8001:8001  # Metrics port
    volumes:
      - /path/to/xandikos/data:/data
    environment:
      # Core settings (all optional - defaults shown)
      # - PORT=8000
      # - METRICS_PORT=8001
      # - LISTEN_ADDRESS=0.0.0.0
      # - DATA_DIR=/data
      # - CURRENT_USER_PRINCIPAL=/user/
      # - ROUTE_PREFIX=/

      # Auto-create directories and default calendar/addressbook
      - AUTOCREATE=true
      - DEFAULTS=true

      # Debug options
      # - DEBUG=false
      # - DUMP_DAV_XML=false

      # Compatibility mode for buggy clients
      # - NO_STRICT=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
