---
name: Disperse configuration

"on":
  - push
  - pull_request

jobs:
  disperse:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: jelmer/action-disperse-validate@v2
